### PR TITLE
Automate exe deployment to releases

### PR DESCRIPTION
**Pull request by SaffatHasan**
Automatically generate the executables on every push and attach them to releases/tags when created.

Please note that I had to run PyInstaller to regenerate the spec files. Also, `hooksconfig={}` needed to be removed, which I suspect is due to the pyinstaller action using an older version of python.

See [test release](https://github.com/SaffatHasan/LostArkFishingBot/releases/tag/test2) and the corresponding [deployment action](https://github.com/SaffatHasan/LostArkFishingBot/actions/runs/2333276261) (note that password is **password**)

### CODE REVIEW

**Comment by SaffatHasan** [comment]
I've just now noticed that you lock the generated zip file as mentioned in #2

**Comment by DamienShahan** [comment]
These are great additions, however the executable files require then entire folder to run. 

Would changing .github/workflows/release.yaml line 41 from 
`dist/windows/${{ matrix.script_name }}.exe`
to
`dist/windows/${{ matrix.script_name }}/`
be enough to automatically upload the entire folder?

**Comment by SaffatHasan** [comment]
I'll look into this when I get the chance, though I'll be on vacation next week with no internet

**Comment by SaffatHasan** [comment]
Should be good to go now.

I wasn't able to revert the changes to the `*.spec` files and I didn't think it was worth troubleshooting to preserve. See [this branch](https://github.com/SaffatHasan/LostArkFishingBot/tree/revert-spec) for the failing action.

You *must* create the repository secret 
image in order to use this PR.

**Comment by SaffatHasan** [comment]
@DamienShahan should I close/delete this?

**Pull request closed without merging**
